// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/request.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type METRIC_TYPE int32

const (
	METRIC_TYPE_METRIC_UNKNOWN        METRIC_TYPE = 0
	METRIC_TYPE_METRIC_VALUE          METRIC_TYPE = 1
	METRIC_TYPE_METRIC_COUNT          METRIC_TYPE = 2
	METRIC_TYPE_METRIC_DISTINCT_COUNT METRIC_TYPE = 3
	METRIC_TYPE_METRIC_SUM            METRIC_TYPE = 4
	METRIC_TYPE_METRIC_ADD            METRIC_TYPE = 5
	METRIC_TYPE_METRIC_SUBTRACT       METRIC_TYPE = 6
	METRIC_TYPE_METRIC_MULTIPLY       METRIC_TYPE = 7
	METRIC_TYPE_METRIC_DIVIDE         METRIC_TYPE = 8
	METRIC_TYPE_METRIC_EXPRESSION     METRIC_TYPE = 20
	METRIC_TYPE_METRIC_POST           METRIC_TYPE = 99
)

var METRIC_TYPE_name = map[int32]string{
	0:  "METRIC_UNKNOWN",
	1:  "METRIC_VALUE",
	2:  "METRIC_COUNT",
	3:  "METRIC_DISTINCT_COUNT",
	4:  "METRIC_SUM",
	5:  "METRIC_ADD",
	6:  "METRIC_SUBTRACT",
	7:  "METRIC_MULTIPLY",
	8:  "METRIC_DIVIDE",
	20: "METRIC_EXPRESSION",
	99: "METRIC_POST",
}

var METRIC_TYPE_value = map[string]int32{
	"METRIC_UNKNOWN":        0,
	"METRIC_VALUE":          1,
	"METRIC_COUNT":          2,
	"METRIC_DISTINCT_COUNT": 3,
	"METRIC_SUM":            4,
	"METRIC_ADD":            5,
	"METRIC_SUBTRACT":       6,
	"METRIC_MULTIPLY":       7,
	"METRIC_DIVIDE":         8,
	"METRIC_EXPRESSION":     20,
	"METRIC_POST":           99,
}

func (x METRIC_TYPE) String() string {
	return proto.EnumName(METRIC_TYPE_name, int32(x))
}

func (METRIC_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{0}
}

type FILTER_OPERATOR_TYPE int32

const (
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_UNKNOWN        FILTER_OPERATOR_TYPE = 0
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_IN             FILTER_OPERATOR_TYPE = 1
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_NOT_IN         FILTER_OPERATOR_TYPE = 2
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_LESS_EQUALS    FILTER_OPERATOR_TYPE = 3
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_LESS           FILTER_OPERATOR_TYPE = 4
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_GREATER_EQUALS FILTER_OPERATOR_TYPE = 5
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_GREATER        FILTER_OPERATOR_TYPE = 6
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_LIKE           FILTER_OPERATOR_TYPE = 7
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_EXTENSION      FILTER_OPERATOR_TYPE = 10
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_AND            FILTER_OPERATOR_TYPE = 101
	FILTER_OPERATOR_TYPE_FILTER_OPERATOR_OR             FILTER_OPERATOR_TYPE = 102
)

var FILTER_OPERATOR_TYPE_name = map[int32]string{
	0:   "FILTER_OPERATOR_UNKNOWN",
	1:   "FILTER_OPERATOR_IN",
	2:   "FILTER_OPERATOR_NOT_IN",
	3:   "FILTER_OPERATOR_LESS_EQUALS",
	4:   "FILTER_OPERATOR_LESS",
	5:   "FILTER_OPERATOR_GREATER_EQUALS",
	6:   "FILTER_OPERATOR_GREATER",
	7:   "FILTER_OPERATOR_LIKE",
	10:  "FILTER_OPERATOR_EXTENSION",
	101: "FILTER_OPERATOR_AND",
	102: "FILTER_OPERATOR_OR",
}

var FILTER_OPERATOR_TYPE_value = map[string]int32{
	"FILTER_OPERATOR_UNKNOWN":        0,
	"FILTER_OPERATOR_IN":             1,
	"FILTER_OPERATOR_NOT_IN":         2,
	"FILTER_OPERATOR_LESS_EQUALS":    3,
	"FILTER_OPERATOR_LESS":           4,
	"FILTER_OPERATOR_GREATER_EQUALS": 5,
	"FILTER_OPERATOR_GREATER":        6,
	"FILTER_OPERATOR_LIKE":           7,
	"FILTER_OPERATOR_EXTENSION":      10,
	"FILTER_OPERATOR_AND":            101,
	"FILTER_OPERATOR_OR":             102,
}

func (x FILTER_OPERATOR_TYPE) String() string {
	return proto.EnumName(FILTER_OPERATOR_TYPE_name, int32(x))
}

func (FILTER_OPERATOR_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{1}
}

type VALUE_TYPE int32

const (
	VALUE_TYPE_VALUE_UNKNOWN VALUE_TYPE = 0
	VALUE_TYPE_VALUE_STRING  VALUE_TYPE = 1
	VALUE_TYPE_VALUE_INTEGER VALUE_TYPE = 2
	VALUE_TYPE_VALUE_FLOAT   VALUE_TYPE = 3
)

var VALUE_TYPE_name = map[int32]string{
	0: "VALUE_UNKNOWN",
	1: "VALUE_STRING",
	2: "VALUE_INTEGER",
	3: "VALUE_FLOAT",
}

var VALUE_TYPE_value = map[string]int32{
	"VALUE_UNKNOWN": 0,
	"VALUE_STRING":  1,
	"VALUE_INTEGER": 2,
	"VALUE_FLOAT":   3,
}

func (x VALUE_TYPE) String() string {
	return proto.EnumName(VALUE_TYPE_name, int32(x))
}

func (VALUE_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{2}
}

type ORDER_DIRECTION_TYPE int32

const (
	ORDER_DIRECTION_TYPE_ORDER_DIRECTION_UNKNOWN    ORDER_DIRECTION_TYPE = 0
	ORDER_DIRECTION_TYPE_ORDER_DIRECTION_ASCENDING  ORDER_DIRECTION_TYPE = 1
	ORDER_DIRECTION_TYPE_ORDER_DIRECTION_DESCENDING ORDER_DIRECTION_TYPE = 2
)

var ORDER_DIRECTION_TYPE_name = map[int32]string{
	0: "ORDER_DIRECTION_UNKNOWN",
	1: "ORDER_DIRECTION_ASCENDING",
	2: "ORDER_DIRECTION_DESCENDING",
}

var ORDER_DIRECTION_TYPE_value = map[string]int32{
	"ORDER_DIRECTION_UNKNOWN":    0,
	"ORDER_DIRECTION_ASCENDING":  1,
	"ORDER_DIRECTION_DESCENDING": 2,
}

func (x ORDER_DIRECTION_TYPE) String() string {
	return proto.EnumName(ORDER_DIRECTION_TYPE_name, int32(x))
}

func (ORDER_DIRECTION_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{3}
}

type DATA_SOURCE_TYPE int32

const (
	DATA_SOURCE_TYPE_DATA_SOURCE_UNKNOWN    DATA_SOURCE_TYPE = 0
	DATA_SOURCE_TYPE_DATA_SOURCE_CLICKHOUSE DATA_SOURCE_TYPE = 1
	DATA_SOURCE_TYPE_DATA_SOURCE_DRUID      DATA_SOURCE_TYPE = 2
	DATA_SOURCE_TYPE_DATA_SOURCE_KYLIN      DATA_SOURCE_TYPE = 3
	DATA_SOURCE_TYPE_DATA_SOURCE_PRESTO     DATA_SOURCE_TYPE = 4
)

var DATA_SOURCE_TYPE_name = map[int32]string{
	0: "DATA_SOURCE_UNKNOWN",
	1: "DATA_SOURCE_CLICKHOUSE",
	2: "DATA_SOURCE_DRUID",
	3: "DATA_SOURCE_KYLIN",
	4: "DATA_SOURCE_PRESTO",
}

var DATA_SOURCE_TYPE_value = map[string]int32{
	"DATA_SOURCE_UNKNOWN":    0,
	"DATA_SOURCE_CLICKHOUSE": 1,
	"DATA_SOURCE_DRUID":      2,
	"DATA_SOURCE_KYLIN":      3,
	"DATA_SOURCE_PRESTO":     4,
}

func (x DATA_SOURCE_TYPE) String() string {
	return proto.EnumName(DATA_SOURCE_TYPE_name, int32(x))
}

func (DATA_SOURCE_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{4}
}

type Metric struct {
	Type                 METRIC_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=proto.METRIC_TYPE" json:"type,omitempty"`
	Table                string      `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FieldName            string      `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	Children             []*Metric   `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{0}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetType() METRIC_TYPE {
	if m != nil {
		return m.Type
	}
	return METRIC_TYPE_METRIC_UNKNOWN
}

func (m *Metric) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metric) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *Metric) GetChildren() []*Metric {
	if m != nil {
		return m.Children
	}
	return nil
}

type Dimension struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FieldName            string   `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dimension) Reset()         { *m = Dimension{} }
func (m *Dimension) String() string { return proto.CompactTextString(m) }
func (*Dimension) ProtoMessage()    {}
func (*Dimension) Descriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{1}
}

func (m *Dimension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dimension.Unmarshal(m, b)
}
func (m *Dimension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dimension.Marshal(b, m, deterministic)
}
func (m *Dimension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dimension.Merge(m, src)
}
func (m *Dimension) XXX_Size() int {
	return xxx_messageInfo_Dimension.Size(m)
}
func (m *Dimension) XXX_DiscardUnknown() {
	xxx_messageInfo_Dimension.DiscardUnknown(m)
}

var xxx_messageInfo_Dimension proto.InternalMessageInfo

func (m *Dimension) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Dimension) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dimension) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

type Filter struct {
	OperatorType         FILTER_OPERATOR_TYPE `protobuf:"varint,1,opt,name=operator_type,json=operatorType,proto3,enum=proto.FILTER_OPERATOR_TYPE" json:"operator_type,omitempty"`
	ValueType            VALUE_TYPE           `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=proto.VALUE_TYPE" json:"value_type,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value                []string             `protobuf:"bytes,4,rep,name=value,proto3" json:"value,omitempty"`
	Children             []*Filter            `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{2}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetOperatorType() FILTER_OPERATOR_TYPE {
	if m != nil {
		return m.OperatorType
	}
	return FILTER_OPERATOR_TYPE_FILTER_OPERATOR_UNKNOWN
}

func (m *Filter) GetValueType() VALUE_TYPE {
	if m != nil {
		return m.ValueType
	}
	return VALUE_TYPE_VALUE_UNKNOWN
}

func (m *Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Filter) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Filter) GetChildren() []*Filter {
	if m != nil {
		return m.Children
	}
	return nil
}

type JoinOn struct {
	Key1                 string   `protobuf:"bytes,1,opt,name=key1,proto3" json:"key1,omitempty"`
	Key2                 string   `protobuf:"bytes,2,opt,name=key2,proto3" json:"key2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinOn) Reset()         { *m = JoinOn{} }
func (m *JoinOn) String() string { return proto.CompactTextString(m) }
func (*JoinOn) ProtoMessage()    {}
func (*JoinOn) Descriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{3}
}

func (m *JoinOn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinOn.Unmarshal(m, b)
}
func (m *JoinOn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinOn.Marshal(b, m, deterministic)
}
func (m *JoinOn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinOn.Merge(m, src)
}
func (m *JoinOn) XXX_Size() int {
	return xxx_messageInfo_JoinOn.Size(m)
}
func (m *JoinOn) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinOn.DiscardUnknown(m)
}

var xxx_messageInfo_JoinOn proto.InternalMessageInfo

func (m *JoinOn) GetKey1() string {
	if m != nil {
		return m.Key1
	}
	return ""
}

func (m *JoinOn) GetKey2() string {
	if m != nil {
		return m.Key2
	}
	return ""
}

type Join struct {
	Database1            string    `protobuf:"bytes,1,opt,name=database1,proto3" json:"database1,omitempty"`
	Database2            string    `protobuf:"bytes,2,opt,name=database2,proto3" json:"database2,omitempty"`
	Table1               string    `protobuf:"bytes,3,opt,name=table1,proto3" json:"table1,omitempty"`
	Table2               string    `protobuf:"bytes,4,opt,name=table2,proto3" json:"table2,omitempty"`
	On                   []*JoinOn `protobuf:"bytes,5,rep,name=on,proto3" json:"on,omitempty"`
	Filters              []*Filter `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Join) Reset()         { *m = Join{} }
func (m *Join) String() string { return proto.CompactTextString(m) }
func (*Join) ProtoMessage()    {}
func (*Join) Descriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{4}
}

func (m *Join) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Join.Unmarshal(m, b)
}
func (m *Join) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Join.Marshal(b, m, deterministic)
}
func (m *Join) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join.Merge(m, src)
}
func (m *Join) XXX_Size() int {
	return xxx_messageInfo_Join.Size(m)
}
func (m *Join) XXX_DiscardUnknown() {
	xxx_messageInfo_Join.DiscardUnknown(m)
}

var xxx_messageInfo_Join proto.InternalMessageInfo

func (m *Join) GetDatabase1() string {
	if m != nil {
		return m.Database1
	}
	return ""
}

func (m *Join) GetDatabase2() string {
	if m != nil {
		return m.Database2
	}
	return ""
}

func (m *Join) GetTable1() string {
	if m != nil {
		return m.Table1
	}
	return ""
}

func (m *Join) GetTable2() string {
	if m != nil {
		return m.Table2
	}
	return ""
}

func (m *Join) GetOn() []*JoinOn {
	if m != nil {
		return m.On
	}
	return nil
}

func (m *Join) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

type OrderBy struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Direction            ORDER_DIRECTION_TYPE `protobuf:"varint,2,opt,name=direction,proto3,enum=proto.ORDER_DIRECTION_TYPE" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderBy) Reset()         { *m = OrderBy{} }
func (m *OrderBy) String() string { return proto.CompactTextString(m) }
func (*OrderBy) ProtoMessage()    {}
func (*OrderBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{5}
}

func (m *OrderBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBy.Unmarshal(m, b)
}
func (m *OrderBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBy.Marshal(b, m, deterministic)
}
func (m *OrderBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBy.Merge(m, src)
}
func (m *OrderBy) XXX_Size() int {
	return xxx_messageInfo_OrderBy.Size(m)
}
func (m *OrderBy) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBy.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBy proto.InternalMessageInfo

func (m *OrderBy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderBy) GetDirection() ORDER_DIRECTION_TYPE {
	if m != nil {
		return m.Direction
	}
	return ORDER_DIRECTION_TYPE_ORDER_DIRECTION_UNKNOWN
}

type Limit struct {
	Limit                uint64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Limit) Reset()         { *m = Limit{} }
func (m *Limit) String() string { return proto.CompactTextString(m) }
func (*Limit) ProtoMessage()    {}
func (*Limit) Descriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{6}
}

func (m *Limit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Limit.Unmarshal(m, b)
}
func (m *Limit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Limit.Marshal(b, m, deterministic)
}
func (m *Limit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limit.Merge(m, src)
}
func (m *Limit) XXX_Size() int {
	return xxx_messageInfo_Limit.Size(m)
}
func (m *Limit) XXX_DiscardUnknown() {
	xxx_messageInfo_Limit.DiscardUnknown(m)
}

var xxx_messageInfo_Limit proto.InternalMessageInfo

func (m *Limit) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Limit) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DataSource struct {
	Type                 DATA_SOURCE_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=proto.DATA_SOURCE_TYPE" json:"type,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DataSource) Reset()         { *m = DataSource{} }
func (m *DataSource) String() string { return proto.CompactTextString(m) }
func (*DataSource) ProtoMessage()    {}
func (*DataSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{7}
}

func (m *DataSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSource.Unmarshal(m, b)
}
func (m *DataSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSource.Marshal(b, m, deterministic)
}
func (m *DataSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSource.Merge(m, src)
}
func (m *DataSource) XXX_Size() int {
	return xxx_messageInfo_DataSource.Size(m)
}
func (m *DataSource) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSource.DiscardUnknown(m)
}

var xxx_messageInfo_DataSource proto.InternalMessageInfo

func (m *DataSource) GetType() DATA_SOURCE_TYPE {
	if m != nil {
		return m.Type
	}
	return DATA_SOURCE_TYPE_DATA_SOURCE_UNKNOWN
}

func (m *DataSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	Metrics              []*Metric    `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Dimensions           []*Dimension `protobuf:"bytes,2,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Filters              []*Filter    `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	Joins                []*Join      `protobuf:"bytes,4,rep,name=joins,proto3" json:"joins,omitempty"`
	Orders               []*OrderBy   `protobuf:"bytes,5,rep,name=orders,proto3" json:"orders,omitempty"`
	Limit                uint64       `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	DataSource           *DataSource  `protobuf:"bytes,7,opt,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_336e959edb61afc4, []int{8}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Request) GetDimensions() []*Dimension {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *Request) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *Request) GetJoins() []*Join {
	if m != nil {
		return m.Joins
	}
	return nil
}

func (m *Request) GetOrders() []*OrderBy {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *Request) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Request) GetDataSource() *DataSource {
	if m != nil {
		return m.DataSource
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.METRIC_TYPE", METRIC_TYPE_name, METRIC_TYPE_value)
	proto.RegisterEnum("proto.FILTER_OPERATOR_TYPE", FILTER_OPERATOR_TYPE_name, FILTER_OPERATOR_TYPE_value)
	proto.RegisterEnum("proto.VALUE_TYPE", VALUE_TYPE_name, VALUE_TYPE_value)
	proto.RegisterEnum("proto.ORDER_DIRECTION_TYPE", ORDER_DIRECTION_TYPE_name, ORDER_DIRECTION_TYPE_value)
	proto.RegisterEnum("proto.DATA_SOURCE_TYPE", DATA_SOURCE_TYPE_name, DATA_SOURCE_TYPE_value)
	proto.RegisterType((*Metric)(nil), "proto.Metric")
	proto.RegisterType((*Dimension)(nil), "proto.Dimension")
	proto.RegisterType((*Filter)(nil), "proto.Filter")
	proto.RegisterType((*JoinOn)(nil), "proto.JoinOn")
	proto.RegisterType((*Join)(nil), "proto.Join")
	proto.RegisterType((*OrderBy)(nil), "proto.OrderBy")
	proto.RegisterType((*Limit)(nil), "proto.Limit")
	proto.RegisterType((*DataSource)(nil), "proto.DataSource")
	proto.RegisterType((*Request)(nil), "proto.Request")
}

func init() { proto.RegisterFile("api/proto/request.proto", fileDescriptor_336e959edb61afc4) }

var fileDescriptor_336e959edb61afc4 = []byte{
	// 989 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xdd, 0x76, 0xdb, 0x44,
	0x10, 0x46, 0xf2, 0x5f, 0x3d, 0x6e, 0xd2, 0xcd, 0x36, 0x3f, 0x4e, 0x42, 0x8a, 0xf1, 0x45, 0x09,
	0xe1, 0x34, 0x6e, 0xcd, 0xe1, 0x82, 0x3b, 0x14, 0x6b, 0x13, 0x44, 0x1c, 0x29, 0xac, 0xd6, 0x25,
	0xe1, 0xc6, 0x47, 0xb1, 0x37, 0x54, 0xe0, 0x58, 0xae, 0xa4, 0xc0, 0xc9, 0x43, 0xf0, 0x12, 0x1c,
	0x9e, 0x82, 0x77, 0xe0, 0x82, 0x87, 0xe0, 0x3d, 0x38, 0xbb, 0x5a, 0xfd, 0x54, 0xa8, 0xbd, 0xf2,
	0xce, 0xf7, 0xcd, 0x68, 0x66, 0xbe, 0xd9, 0xd9, 0x63, 0xd8, 0xf1, 0x56, 0xfe, 0x60, 0x15, 0x06,
	0x71, 0x30, 0x08, 0xf9, 0xdb, 0x7b, 0x1e, 0xc5, 0xc7, 0xd2, 0xc2, 0x0d, 0xf9, 0xd3, 0xff, 0x53,
	0x83, 0xe6, 0x05, 0x8f, 0x43, 0x7f, 0x86, 0x9f, 0x43, 0x3d, 0x7e, 0x58, 0xf1, 0xae, 0xd6, 0xd3,
	0x0e, 0xd7, 0x87, 0x38, 0xf1, 0x3b, 0xbe, 0x20, 0x8c, 0x5a, 0xa3, 0x29, 0xbb, 0xbe, 0x24, 0x54,
	0xf2, 0x78, 0x13, 0x1a, 0xb1, 0x77, 0xb3, 0xe0, 0x5d, 0xbd, 0xa7, 0x1d, 0xb6, 0x69, 0x62, 0x60,
	0x0c, 0xf5, 0xa5, 0x77, 0xc7, 0xbb, 0x35, 0x09, 0xca, 0x33, 0x3e, 0x00, 0xb8, 0xf5, 0xf9, 0x62,
	0x3e, 0x95, 0x4c, 0x5d, 0x32, 0x6d, 0x89, 0xd8, 0x82, 0xfe, 0x1c, 0x1e, 0xcd, 0xde, 0xf8, 0x8b,
	0x79, 0xc8, 0x97, 0xdd, 0x46, 0xaf, 0x76, 0xd8, 0x19, 0xae, 0xa5, 0x49, 0x65, 0x45, 0x34, 0xa3,
	0xfb, 0x0c, 0xda, 0xa6, 0x7f, 0xc7, 0x97, 0x91, 0x1f, 0x2c, 0xf3, 0x02, 0xb4, 0xaa, 0x02, 0xf4,
	0xf7, 0x16, 0x50, 0x2b, 0x15, 0xd0, 0xff, 0x47, 0x83, 0xe6, 0xa9, 0xbf, 0x88, 0x79, 0x88, 0xbf,
	0x81, 0xb5, 0x60, 0xc5, 0x43, 0x2f, 0x0e, 0xc2, 0x69, 0x41, 0x85, 0x7d, 0x55, 0xd0, 0xa9, 0x35,
	0x66, 0x84, 0x4e, 0x9d, 0x4b, 0x42, 0x0d, 0xe6, 0xd0, 0x44, 0x8e, 0xc7, 0x69, 0x04, 0x13, 0xb2,
	0xbc, 0x04, 0xf8, 0xd5, 0x5b, 0xdc, 0xf3, 0x24, 0x5c, 0x97, 0xe1, 0x1b, 0x2a, 0xfc, 0xb5, 0x31,
	0x9e, 0x90, 0x24, 0xa8, 0x2d, 0x9d, 0x64, 0x44, 0x95, 0x64, 0x9b, 0xd0, 0x90, 0x0e, 0xdd, 0x7a,
	0xaf, 0x26, 0x7a, 0x93, 0xc6, 0x07, 0x94, 0x4a, 0xca, 0x2f, 0x28, 0xf5, 0x12, 0x9a, 0xdf, 0x05,
	0xfe, 0xd2, 0x59, 0x8a, 0xcf, 0xff, 0xc2, 0x1f, 0x5e, 0x29, 0x95, 0xe4, 0x59, 0x61, 0xc3, 0x54,
	0x24, 0x71, 0xee, 0xff, 0xa5, 0x41, 0x5d, 0x84, 0xe0, 0x8f, 0xa1, 0x3d, 0xf7, 0x62, 0xef, 0xc6,
	0x8b, 0x78, 0x1a, 0x95, 0x03, 0x45, 0x36, 0x8d, 0xcf, 0x01, 0xbc, 0x0d, 0x4d, 0x39, 0x86, 0x57,
	0xaa, 0x1b, 0x65, 0x65, 0xf8, 0x50, 0x8d, 0x5f, 0x59, 0xf8, 0x00, 0xf4, 0xa0, 0xdc, 0x4b, 0x52,
	0x37, 0xd5, 0x83, 0x25, 0xfe, 0x0c, 0x5a, 0xb7, 0xb2, 0xb3, 0xa8, 0xdb, 0xac, 0xea, 0x37, 0x65,
	0xfb, 0x57, 0xd0, 0x72, 0xc2, 0x39, 0x0f, 0x4f, 0x1e, 0x32, 0x39, 0xb5, 0x82, 0x9c, 0x5f, 0x43,
	0x7b, 0xee, 0x87, 0x7c, 0x16, 0xfb, 0xc1, 0x52, 0xcd, 0x24, 0x1d, 0xa9, 0x43, 0x4d, 0x42, 0xa7,
	0xa6, 0x45, 0xc9, 0x88, 0x59, 0x8e, 0xad, 0xa6, 0x93, 0x79, 0xf7, 0xbf, 0x82, 0xc6, 0xd8, 0xbf,
	0xf3, 0x63, 0x31, 0x92, 0x85, 0x38, 0xc8, 0x0f, 0xd7, 0x69, 0x62, 0x88, 0xc6, 0x82, 0xdb, 0xdb,
	0x88, 0xc7, 0xf2, 0xb3, 0x75, 0xaa, 0xac, 0xfe, 0x05, 0x80, 0xe9, 0xc5, 0x9e, 0x1b, 0xdc, 0x87,
	0x33, 0x8e, 0xbf, 0x78, 0x67, 0xa7, 0x76, 0x54, 0x6a, 0xd3, 0x60, 0xc6, 0xd4, 0x75, 0x26, 0x74,
	0x44, 0x8a, 0x8b, 0x55, 0x71, 0x83, 0xfb, 0x7f, 0xe8, 0xd0, 0xa2, 0xc9, 0xe2, 0x0a, 0x51, 0xee,
	0xe4, 0x62, 0x44, 0x5d, 0xad, 0x6a, 0x5d, 0x52, 0x56, 0x5c, 0xc5, 0x79, 0xba, 0x2d, 0x51, 0x57,
	0x97, 0xbe, 0x28, 0xcd, 0x9d, 0x12, 0xb4, 0xe0, 0x53, 0xd4, 0xbb, 0xf6, 0x21, 0xbd, 0xf1, 0xa7,
	0xd0, 0xf8, 0x39, 0xf0, 0x97, 0x91, 0xbc, 0x9f, 0x9d, 0x61, 0xa7, 0x30, 0x3a, 0x9a, 0x30, 0xf8,
	0x39, 0x34, 0x03, 0x31, 0x92, 0x48, 0x8d, 0x77, 0x3d, 0x15, 0x3c, 0x99, 0x13, 0x55, 0x6c, 0xae,
	0x6b, 0xb3, 0xa8, 0xeb, 0x10, 0x3a, 0xe2, 0x56, 0x4d, 0x23, 0x29, 0x60, 0xb7, 0xd5, 0xd3, 0x0e,
	0x3b, 0xd9, 0x1e, 0xe5, 0xca, 0x52, 0x98, 0x67, 0xe7, 0xa3, 0x7f, 0x35, 0xe8, 0x14, 0xde, 0x29,
	0x8c, 0x61, 0x5d, 0x99, 0x13, 0xfb, 0xdc, 0x76, 0x7e, 0xb0, 0xd1, 0x47, 0x18, 0xc1, 0x63, 0x85,
	0xc9, 0x65, 0x44, 0x5a, 0x01, 0x19, 0x39, 0x13, 0x9b, 0x21, 0x1d, 0xef, 0xc2, 0x96, 0x42, 0x4c,
	0xcb, 0x65, 0x96, 0x3d, 0x62, 0x8a, 0xaa, 0xe1, 0x75, 0x00, 0x45, 0xb9, 0x93, 0x0b, 0x54, 0x2f,
	0xd8, 0x86, 0x69, 0xa2, 0x06, 0x7e, 0x0a, 0x4f, 0x32, 0xfe, 0x84, 0x51, 0x63, 0xc4, 0x50, 0xb3,
	0x00, 0x5e, 0x4c, 0xc6, 0xcc, 0xba, 0x1c, 0x5f, 0xa3, 0x16, 0xde, 0x80, 0xb5, 0x2c, 0xc9, 0x6b,
	0xcb, 0x24, 0xe8, 0x11, 0xde, 0x82, 0x0d, 0x05, 0x91, 0xab, 0x4b, 0x4a, 0x5c, 0xd7, 0x72, 0x6c,
	0xb4, 0x89, 0x9f, 0x64, 0x5d, 0x5d, 0x3a, 0x2e, 0x43, 0xb3, 0xa3, 0xbf, 0x75, 0xd8, 0xac, 0x7a,
	0x89, 0xf0, 0x3e, 0xec, 0x94, 0xf1, 0xbc, 0xf3, 0x6d, 0xc0, 0x65, 0xd2, 0xb2, 0x91, 0x86, 0xf7,
	0x60, 0xbb, 0x8c, 0xdb, 0x0e, 0x13, 0x9c, 0x8e, 0x3f, 0x81, 0xfd, 0x32, 0x37, 0x26, 0xae, 0x3b,
	0x25, 0xdf, 0x4f, 0x8c, 0xb1, 0x8b, 0x6a, 0xb8, 0xfb, 0xff, 0x4a, 0x84, 0x03, 0xaa, 0xe3, 0x3e,
	0x3c, 0x2b, 0x33, 0x67, 0x94, 0x18, 0x02, 0x50, 0xd1, 0x8d, 0xaa, 0x7a, 0x95, 0x0f, 0x6a, 0x56,
	0x7e, 0xda, 0x3a, 0x27, 0xa8, 0x85, 0x0f, 0x60, 0xb7, 0xcc, 0x90, 0x2b, 0x46, 0x6c, 0xa9, 0x17,
	0xe0, 0x1d, 0x78, 0x5a, 0xa6, 0x0d, 0xdb, 0x44, 0xbc, 0x4a, 0x01, 0x87, 0xa2, 0xdb, 0xa3, 0x09,
	0x40, 0xfe, 0x32, 0x8b, 0xc1, 0x24, 0xd6, 0x3b, 0x97, 0x26, 0x81, 0x5c, 0x46, 0x2d, 0xfb, 0x0c,
	0x69, 0xb9, 0x93, 0x65, 0x33, 0x72, 0x46, 0x28, 0xd2, 0xc5, 0x98, 0x12, 0xe8, 0x74, 0xec, 0x18,
	0x0c, 0xd5, 0x8e, 0x42, 0xd8, 0xac, 0x7a, 0x5c, 0x44, 0xd7, 0x65, 0x3c, 0x4f, 0x75, 0x00, 0xbb,
	0x65, 0xd2, 0x70, 0x47, 0xc4, 0x36, 0x93, 0xbc, 0xcf, 0x60, 0xaf, 0x4c, 0x9b, 0x24, 0xe3, 0xf5,
	0xa3, 0xdf, 0x35, 0x40, 0xe5, 0x67, 0x45, 0x08, 0x52, 0xc4, 0xf2, 0x64, 0x7b, 0xb0, 0x5d, 0x24,
	0x46, 0x63, 0x6b, 0x74, 0xfe, 0xad, 0x33, 0x71, 0xc5, 0x5a, 0x6c, 0xc1, 0x46, 0x91, 0x33, 0xe9,
	0xc4, 0x32, 0x91, 0x5e, 0x86, 0xcf, 0xaf, 0xc7, 0x96, 0x8d, 0x6a, 0x42, 0xda, 0x22, 0x2c, 0x6e,
	0x2f, 0x73, 0x50, 0xfd, 0x64, 0xf0, 0xe3, 0x8b, 0xde, 0x4f, 0x7e, 0xfc, 0xe6, 0xfe, 0xe6, 0x78,
	0x16, 0xdc, 0x0d, 0xbc, 0xdf, 0xbc, 0x98, 0x87, 0xb3, 0x60, 0x11, 0x84, 0x2b, 0xbe, 0x1c, 0x04,
	0x0b, 0x6f, 0xf5, 0x22, 0x7a, 0xbb, 0x18, 0x64, 0xff, 0x4e, 0x6e, 0x9a, 0xf2, 0xe7, 0xcb, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x31, 0xba, 0xb8, 0x31, 0xb1, 0x08, 0x00, 0x00,
}
